version: "3.9"

services:
  mysql-database:
    container_name: mysql-book-database
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: book_db